name: Flutter Build

on:
  workflow_dispatch:
  push:
    branches:
      - main  # veya kendi branch ismini yaz

jobs:
  build:
    name: Build Flutter App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'

      - name: Add Permissions to AndroidManifest.xml
        run: |
          MANIFEST=android/app/src/main/AndroidManifest.xml
          echo "Checking and adding permissions if missing..."
          grep -q 'android.permission.INTERNET' $MANIFEST || sed -i '/<manifest /a \
          <uses-permission android:name="android.permission.INTERNET" />' $MANIFEST
          grep -q 'android.permission.ACCESS_NETWORK_STATE' $MANIFEST || sed -i '/<manifest /a \
          <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />' $MANIFEST
          grep -q 'android.permission.ACCESS_WIFI_STATE' $MANIFEST || sed -i '/<manifest /a \
          <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />' $MANIFEST
          grep -q 'android.permission.READ_EXTERNAL_STORAGE' $MANIFEST || sed -i '/<manifest /a \
          <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />' $MANIFEST
          grep -q 'android.permission.WRITE_EXTERNAL_STORAGE' $MANIFEST || sed -i '/<manifest /a \
          <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />' $MANIFEST
          echo "Permissions checked/added."

      - name: Install Dependencies
        run: flutter pub get

      - name: Analyze Code
        run: flutter analyze

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
