name: Flutter Build

on:
  workflow_dispatch:
  push:
    branches:
      - main  # veya kendi branch ismini yaz

jobs:
  build:
    name: Build Flutter App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'

      - name: Install Dependencies
        run: flutter pub get

      - name: Analyze Code
        run: flutter analyze

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4  # 🔄 Güncellenmiş sürüm
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
